#!/usr/bin/env bash
# FORGE Updater -- Standalone terminal script
# Equivalent to /forge update but runs outside Claude Code.
set -euo pipefail

# Colors (disabled if not a terminal)
if [ -t 1 ]; then
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    BLUE='\033[0;34m'
    RED='\033[0;31m'
    BOLD='\033[1m'
    NC='\033[0m'
else
    GREEN='' YELLOW='' BLUE='' RED='' BOLD='' NC=''
fi

info()  { printf '%b\n' "${BLUE}->${NC} $1"; }
ok()    { printf '%b\n' "${GREEN}ok${NC} $1"; }
warn()  { printf '%b\n' "${YELLOW}!${NC} $1"; }
error() { printf '%b\n' "${RED}x${NC} $1" >&2; }

CLAUDE_DIR="${HOME}/.claude"
FORGE_DIR="${HOME}/.forge"
TMPDIR="/tmp/forge-update-$(date +%Y%m%d-%H%M%S)"
INSTALL_PACK=""
PACK_ONLY=false
AUTO_YES=false
ORIGINAL_ARGS=("$@")

# ---- Parse arguments --------------------------------------------------------

while [[ $# -gt 0 ]]; do
    case "$1" in
        -y|--yes)
            AUTO_YES=true
            shift
            ;;
        --pack)
            INSTALL_PACK="${2:-}"
            shift 2
            ;;
        --only)
            PACK_ONLY=true
            shift
            ;;
        -h|--help)
            echo "Usage: bash update.sh [-y] [--pack business] [--only]"
            echo ""
            echo "  -y, --yes         Accept all prompts automatically"
            echo "  --pack business   Install/update the Business Pack"
            echo "  --only            Only update the pack, skip core skills"
            exit 0
            ;;
        *)
            error "Unknown argument: $1"
            exit 1
            ;;
    esac
done

# ---- Banner -----------------------------------------------------------------

echo ""
printf '%b\n' "${GREEN}FORGE${NC} -- Update"
echo ""

# ---- Pre-checks -------------------------------------------------------------

if [ ! -f "${CLAUDE_DIR}/skills/forge/SKILL.md" ]; then
    error "FORGE is not installed. Run install.sh first:"
    error "  git clone https://github.com/fwehrling/forge.git /tmp/forge && bash /tmp/forge/install.sh"
    exit 1
fi

# Ensure ~/.forge/skills/ exists (may be missing on v1 installations)
mkdir -p "${FORGE_DIR}/skills"

OLD_VERSION="unknown"
if [ -f "${CLAUDE_DIR}/skills/forge/.forge-version" ]; then
    OLD_VERSION="$(cat "${CLAUDE_DIR}/skills/forge/.forge-version" | tr -d '[:space:]')"
fi
info "Current version: v${OLD_VERSION}"

# ---- Clone repo --------------------------------------------------------------

info "Fetching latest version..."
rm -rf "$TMPDIR"
git clone --depth 1 --quiet https://github.com/fwehrling/forge.git "$TMPDIR"

NEW_VERSION="unknown"
if [ -f "${TMPDIR}/VERSION" ]; then
    NEW_VERSION="$(cat "${TMPDIR}/VERSION" | tr -d '[:space:]')"
fi

# Self-update: if the fetched update.sh is newer, re-exec with it
if [ "${FORGE_SELF_UPDATED:-}" != "true" ] && [ -f "${TMPDIR}/update.sh" ]; then
    if ! diff -q "$0" "${TMPDIR}/update.sh" &>/dev/null; then
        info "Newer update.sh detected, restarting with latest version..."
        export FORGE_SELF_UPDATED=true
        exec bash "${TMPDIR}/update.sh" "${ORIGINAL_ARGS[@]}"
    fi
fi

SAME_VERSION=false
if [ "$OLD_VERSION" = "$NEW_VERSION" ]; then
    SAME_VERSION=true
fi

# ---- Compare skills ----------------------------------------------------------

MODIFIED=0
NEW_SKILLS=0
MODIFIED_LIST=""

skill_has_changes() {
    # Compare all tracked files between source and target skill directories.
    # Excludes generated artifacts. Uses a simple for loop (no process substitution)
    # for maximum portability across shells and platforms.
    local src="${1%/}" dst="${2%/}"
    local f rel

    # Check each source file against target (excluding generated artifacts)
    for f in $(find "$src" -type f \
        ! -path '*/.venv/*' \
        ! -path '*/__pycache__/*' \
        ! -name '.DS_Store' \
        ! -name '.forge-version' \
        ! -name '.forge-update-cache' \
        ! -name '*.pyc' \
        2>/dev/null | sort); do

        # Skip the forge-memory CLI symlink/script (generated by setup.sh)
        case "$(basename "$f")" in
            forge-memory) continue ;;
        esac

        rel="${f#"$src"/}"
        if [ ! -f "$dst/$rel" ]; then
            return 0  # new file in source
        fi
        if ! diff -q "$f" "$dst/$rel" &>/dev/null; then
            return 0  # content differs
        fi
    done
    return 1  # no changes
}

compare_skill() {
    local skill_name="$1"
    local source_dir="$2"
    # Hub goes to ~/.claude/skills/, satellites to ~/.forge/skills/
    local target_dir
    if [ "$skill_name" = "forge" ]; then
        target_dir="${CLAUDE_DIR}/skills/${skill_name}"
    else
        target_dir="${FORGE_DIR}/skills/${skill_name}"
    fi

    if [ ! -d "$target_dir" ]; then
        NEW_SKILLS=$((NEW_SKILLS + 1))
        MODIFIED_LIST="${MODIFIED_LIST}\n  ${GREEN}+ new${NC}  ${skill_name}"
        return
    fi

    if skill_has_changes "$source_dir" "$target_dir"; then
        MODIFIED=$((MODIFIED + 1))
        MODIFIED_LIST="${MODIFIED_LIST}\n  ${YELLOW}~ mod${NC}  ${skill_name}"
    fi
}

if [ "$PACK_ONLY" = false ]; then
    for dir in "${TMPDIR}/skills/"*/; do
        [ -d "$dir" ] || continue
        skill_name="$(basename "$dir")"
        compare_skill "$skill_name" "$dir"
    done
fi

# Compare pack skills if requested or already installed
PACK_MODIFIED=0
PACK_LIST=""
if [ -n "$INSTALL_PACK" ] && [ -d "${TMPDIR}/packs/${INSTALL_PACK}" ]; then
    for dir in "${TMPDIR}/packs/${INSTALL_PACK}/"forge-*/; do
        [ -d "$dir" ] || continue
        skill_name="$(basename "$dir")"
        local_dir="${FORGE_DIR}/skills/${skill_name}"
        if [ ! -d "$local_dir" ]; then
            PACK_MODIFIED=$((PACK_MODIFIED + 1))
            PACK_LIST="${PACK_LIST}\n  ${GREEN}+ new${NC}  ${skill_name}"
        elif skill_has_changes "$dir" "$local_dir"; then
            PACK_MODIFIED=$((PACK_MODIFIED + 1))
            PACK_LIST="${PACK_LIST}\n  ${YELLOW}~ mod${NC}  ${skill_name}"
        fi
    done
elif [ -d "${TMPDIR}/packs/business" ]; then
    # Auto-update previously installed business pack skills
    for dir in "${TMPDIR}/packs/business/"forge-*/; do
        [ -d "$dir" ] || continue
        skill_name="$(basename "$dir")"
        if [ -d "${FORGE_DIR}/skills/${skill_name}" ]; then
            if skill_has_changes "$dir" "${FORGE_DIR}/skills/${skill_name}"; then
                PACK_MODIFIED=$((PACK_MODIFIED + 1))
                PACK_LIST="${PACK_LIST}\n  ${YELLOW}~ mod${NC}  ${skill_name} (business)"
            fi
        fi
    done
fi

# Display comparison results
TOTAL_CHANGES=$((MODIFIED + NEW_SKILLS + PACK_MODIFIED))
if [ "$SAME_VERSION" = true ] && [ "$TOTAL_CHANGES" -eq 0 ]; then
    ok "Already up to date (v${NEW_VERSION}) -- nothing to do"
    rm -rf "$TMPDIR"
    echo ""
    exit 0
fi

if [ "$SAME_VERSION" = true ] && [ "$TOTAL_CHANGES" -gt 0 ]; then
    info "Version is v${NEW_VERSION} but some files differ:"
elif [ "$SAME_VERSION" = false ]; then
    info "Updating v${OLD_VERSION} -> v${NEW_VERSION}"
fi

if [ "$TOTAL_CHANGES" -gt 0 ]; then
    [ -n "$MODIFIED_LIST" ] && printf '%b\n' "$MODIFIED_LIST"
    [ -n "$PACK_LIST" ] && printf '%b\n' "$PACK_LIST"
    echo ""
fi

# ---- Copy core skills --------------------------------------------------------

if [ "$PACK_ONLY" = false ]; then
    info "Updating core skills..."

    # Migrate: clean up old forge-* satellites from ~/.claude/skills/ (v1 layout)
    for old_sat in "${CLAUDE_DIR}/skills/"forge-*/; do
        [ -d "$old_sat" ] || continue
        rm -rf "$old_sat"
    done

    for dir in "${TMPDIR}/skills/"*/; do
        [ -d "$dir" ] || continue
        skill_name="$(basename "$dir")"
        if [ "$skill_name" = "forge" ]; then
            # Hub goes to ~/.claude/skills/
            rm -rf "${CLAUDE_DIR}/skills/forge"
            \cp -rf "$dir" "${CLAUDE_DIR}/skills/forge"
        else
            # Satellites go to ~/.forge/skills/
            rm -rf "${FORGE_DIR}/skills/${skill_name}"
            \cp -rf "$dir" "${FORGE_DIR}/skills/${skill_name}"
        fi
    done

    # Remove deprecated skills from both locations
    REMOVED_SKILLS="forge-deploy"
    for skill in $REMOVED_SKILLS; do
        for loc in "${CLAUDE_DIR}/skills/${skill}" "${FORGE_DIR}/skills/${skill}"; do
            if [ -d "$loc" ]; then
                rm -rf "$loc"
                warn "Removed deprecated skill: ${skill}"
            fi
        done
    done

    ok "Core skills updated (hub: ~/.claude/skills/forge/, satellites: ~/.forge/skills/)"
fi

# ---- Copy pack skills --------------------------------------------------------

if [ -n "$INSTALL_PACK" ] && [ -d "${TMPDIR}/packs/${INSTALL_PACK}" ]; then
    info "Installing ${INSTALL_PACK} pack..."
    for dir in "${TMPDIR}/packs/${INSTALL_PACK}/"forge-*/; do
        [ -d "$dir" ] || continue
        skill_name="$(basename "$dir")"
        rm -rf "${FORGE_DIR}/skills/${skill_name}"
        \cp -rf "$dir" "${FORGE_DIR}/skills/${skill_name}"
    done
    ok "Business pack installed to ~/.forge/skills/"
elif [ -d "${TMPDIR}/packs/business" ]; then
    # Auto-update previously installed business pack skills
    local_updated=0
    for dir in "${TMPDIR}/packs/business/"forge-*/; do
        [ -d "$dir" ] || continue
        skill_name="$(basename "$dir")"
        if [ -d "${FORGE_DIR}/skills/${skill_name}" ]; then
            rm -rf "${FORGE_DIR}/skills/${skill_name}"
            \cp -rf "$dir" "${FORGE_DIR}/skills/${skill_name}"
            local_updated=$((local_updated + 1))
        fi
    done
    if [ "$local_updated" -gt 0 ]; then
        ok "Business pack updated (${local_updated} skills)"
    fi
fi

# ---- Update version and cache ------------------------------------------------

info "Updating version and hooks..."

\cp -f "${TMPDIR}/VERSION" "${CLAUDE_DIR}/skills/forge/.forge-version"
rm -f "${CLAUDE_DIR}/skills/forge/.forge-update-cache"

# ---- Update hooks ------------------------------------------------------------

if [ -f "${CLAUDE_DIR}/skills/forge/scripts/forge-hooks-setup.sh" ]; then
    if FORGE_AUTO="$AUTO_YES" bash "${CLAUDE_DIR}/skills/forge/scripts/forge-hooks-setup.sh"; then
        ok "Hooks updated"
    else
        warn "Hook setup failed (non-blocking)"
    fi
fi

# ---- Remove legacy RTK native hook -------------------------------------------
# Deprecated: Claude bypassed the Read|Grep|Glob deny channel by falling back to
# Bash/Node, which cost more tokens than the compression saved.

if [ -f "${CLAUDE_DIR}/hooks/rtk-native-hook.sh" ]; then
    rm -f "${CLAUDE_DIR}/hooks/rtk-native-hook.sh"
    ok "Removed legacy RTK native hook"
fi

if [ -f "${CLAUDE_DIR}/settings.json" ] && command -v python3 &>/dev/null; then
    python3 - "${CLAUDE_DIR}/settings.json" <<'PYSCRIPT' 2>/dev/null || true
import json, sys
sp = sys.argv[1]
with open(sp) as f: cfg = json.load(f)
pre = cfg.get('hooks', {}).get('PreToolUse', [])
before = len(pre)
pre[:] = [e for e in pre if 'rtk-native-hook' not in str(e)]
if len(pre) != before:
    with open(sp, 'w') as f: json.dump(cfg, f, indent=2)
    print('legacy native hook entry removed from settings.json')
PYSCRIPT
fi

# ---- Update CLAUDE.md --------------------------------------------------------

if [ -f "${TMPDIR}/scripts/inject-claude-md.sh" ]; then
    FORGE_YES="$AUTO_YES" bash "${TMPDIR}/scripts/inject-claude-md.sh"
fi

if [ -f "${TMPDIR}/scripts/inject-rtk-claude-md.sh" ]; then
    bash "${TMPDIR}/scripts/inject-rtk-claude-md.sh" 2>/dev/null || true
fi

# ---- Cleanup -----------------------------------------------------------------

rm -rf "$TMPDIR"

# ---- Summary -----------------------------------------------------------------

SKILL_COUNT=$(( $(find "${FORGE_DIR}/skills" -maxdepth 2 -name "SKILL.md" 2>/dev/null | wc -l | tr -d ' ') + 1 ))

echo ""
printf '%b\n' "${GREEN}---------------------------------------------${NC}"
printf '%b\n' "${GREEN}  FORGE updated successfully${NC}"
printf '%b\n' "${GREEN}---------------------------------------------${NC}"
echo ""
if [ "$SAME_VERSION" = true ]; then
    echo "  Version : v${NEW_VERSION} (synced)"
else
    echo "  Version : v${OLD_VERSION} -> v${NEW_VERSION}"
fi
echo "  Skills  : ${SKILL_COUNT} installed"
if [ "$TOTAL_CHANGES" -gt 0 ]; then
    echo "  Changed : ${TOTAL_CHANGES} (${MODIFIED} core, ${NEW_SKILLS} new, ${PACK_MODIFIED} pack)"
else
    echo "  Changed : 0"
fi

# Suggest business pack if not installed
HAS_BUSINESS=false
for bp_skill in forge-marketing forge-copywriting forge-seo forge-geo forge-legal forge-security-pro forge-business-strategy forge-strategy-panel; do
    if [ -d "${FORGE_DIR}/skills/${bp_skill}" ]; then
        HAS_BUSINESS=true
        break
    fi
done

if [ "$HAS_BUSINESS" = false ] && [ -z "$INSTALL_PACK" ]; then
    echo ""
    printf '%b\n' "  ${YELLOW}Tip:${NC} Business Pack available (marketing, SEO, legal, security, strategy)."
    echo "        Run: bash update.sh --pack business"
fi

echo ""
