#!/usr/bin/env bash
# FORGE Memory + Wiki auto-persistence hook -- Claude Code Stop event
#
# Runs at the end of every Claude response. Two stages:
#   1. Memory: consolidate session logs + sync vector index (always)
#   2. Wiki  : if .forge/wiki/ exists, collect changes since last run and
#              queue them as pending-ingest.yaml for the hub to process
#              at the next session start.
#
# Non-blocking, silent, always exits 0.

set -e

find_forge_root() {
  local dir="$PWD"
  while [ "$dir" != "/" ]; do
    if [ -d "$dir/.forge/memory" ] || [ -d "$dir/.forge/wiki" ]; then
      echo "$dir"
      return 0
    fi
    dir="$(dirname "$dir")"
  done
  return 1
}

PROJECT_ROOT=$(find_forge_root) || exit 0
cd "$PROJECT_ROOT"

# --- Stage 1: memory ---------------------------------------------------------
if command -v forge-memory >/dev/null 2>&1 && [ -d ".forge/memory" ]; then
  forge-memory consolidate >/dev/null 2>&1 || true
  forge-memory sync >/dev/null 2>&1 || true
fi

# --- Stage 2: wiki -----------------------------------------------------------
[ -d ".forge/wiki" ] || exit 0
command -v git >/dev/null 2>&1 || exit 0
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || exit 0

STATE_SHA_FILE=".forge/wiki/.last-ingest-sha"
HEAD_SHA=$(git rev-parse HEAD 2>/dev/null || echo "")
[ -z "$HEAD_SHA" ] && exit 0

if [ -f "$STATE_SHA_FILE" ]; then
  LAST_SHA=$(tr -d '[:space:]' < "$STATE_SHA_FILE")
else
  LAST_SHA=""
fi

NEW_COMMITS=""
if [ -n "$LAST_SHA" ] && git cat-file -e "$LAST_SHA^{commit}" 2>/dev/null; then
  NEW_COMMITS=$(git log --pretty=format:"%h|%s" "${LAST_SHA}..HEAD" 2>/dev/null || true)
else
  NEW_COMMITS=$(git log -1 --pretty=format:"%h|%s" HEAD 2>/dev/null || true)
fi

UNCOMMITTED=$(git status --porcelain 2>/dev/null | awk '{print $2}' | sort -u)

if [ -z "$NEW_COMMITS" ] && [ -z "$UNCOMMITTED" ]; then
  exit 0
fi

TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
TS_SLUG=$(date -u +"%Y-%m-%d-%H%M%S")

mkdir -p ".forge/wiki/raw/notes"
NOTE_FILE=".forge/wiki/raw/notes/auto-${TS_SLUG}.md"

{
  echo "---"
  echo "generated: ${TS}"
  echo "source: stop-hook"
  echo "---"
  echo
  echo "# Auto-capture ${TS}"
  echo
  if [ -n "$NEW_COMMITS" ]; then
    echo "## Commits since last capture"
    echo
    echo '```'
    printf '%s\n' "$NEW_COMMITS" | while IFS='|' read -r sha subj; do
      [ -z "$sha" ] && continue
      echo "${sha} ${subj}"
    done
    echo '```'
    echo
  fi
  if [ -n "$UNCOMMITTED" ]; then
    echo "## Uncommitted files"
    echo
    echo '```'
    printf '%s\n' "$UNCOMMITTED"
    echo '```'
    echo
  fi
} > "$NOTE_FILE"

LOG_FILE=".forge/wiki/log.md"
[ -f "$LOG_FILE" ] || printf '# Wiki Log\n\n' > "$LOG_FILE"
COMMIT_COUNT=0
[ -n "$NEW_COMMITS" ] && COMMIT_COUNT=$(printf '%s\n' "$NEW_COMMITS" | wc -l | tr -d ' ')
UNCOMMIT_COUNT=0
[ -n "$UNCOMMITTED" ] && UNCOMMIT_COUNT=$(printf '%s\n' "$UNCOMMITTED" | wc -l | tr -d ' ')
printf -- "- %s auto-capture: %s commits, %s uncommitted -> %s\n" \
  "$TS" "$COMMIT_COUNT" "$UNCOMMIT_COUNT" "$NOTE_FILE" >> "$LOG_FILE"

PENDING=".forge/wiki/pending-ingest.yaml"
if [ ! -f "$PENDING" ]; then
  {
    echo "# Auto-generated by forge-memory-sync Stop hook."
    echo "# Consumed by the FORGE hub at session start (see forge/SKILL.md)."
    echo "sources:"
  } > "$PENDING"
fi
{
  echo "  - type: stop-capture"
  echo "    generated: ${TS}"
  echo "    note: ${NOTE_FILE}"
  if [ -n "$NEW_COMMITS" ]; then
    echo "    commits:"
    printf '%s\n' "$NEW_COMMITS" | while IFS='|' read -r sha subj; do
      [ -z "$sha" ] && continue
      safe_subj=$(printf '%s' "$subj" | sed 's/"/\\"/g')
      echo "      - sha: ${sha}"
      echo "        subject: \"${safe_subj}\""
    done
  fi
  if [ -n "$UNCOMMITTED" ]; then
    echo "    uncommitted:"
    printf '%s\n' "$UNCOMMITTED" | while read -r f; do
      [ -z "$f" ] && continue
      echo "      - ${f}"
    done
  fi
} >> "$PENDING"

printf '%s\n' "$HEAD_SHA" > "$STATE_SHA_FILE"

exit 0
