#!/usr/bin/env bash
# FORGE Memory + Wiki + Release auto-persistence hook -- Claude Code Stop event
#
# Runs at the end of every Claude response. Three stages:
#   1. Memory  : consolidate session logs + sync vector index (always)
#   2. Wiki    : if .forge/wiki/ exists, collect changes since last run and
#                queue them as pending-ingest.yaml for the hub to process
#                at the next session start.
#   3. Release : if HEAD is a release bump (commit msg `chore(release): vX.Y.Z`
#                OR a tag `v*` points at HEAD), queue a flow-state-pending.yaml
#                entry so the hub updates .forge/flow-state.yaml prod_state
#                at the next session start. Prevents drift between prod
#                version and FORGE memory when releases happen outside the
#                FORGE pipeline (direct commits, /cw:release, etc.).
#                Runs independently of Stage 2 so that projects without a
#                wiki still get their release state persisted.
#
# Non-blocking, silent, always exits 0.

set -e

find_forge_root() {
  local dir="$PWD"
  while [ "$dir" != "/" ]; do
    if [ -d "$dir/.forge/memory" ] || [ -d "$dir/.forge/wiki" ]; then
      echo "$dir"
      return 0
    fi
    dir="$(dirname "$dir")"
  done
  return 1
}

PROJECT_ROOT=$(find_forge_root) || exit 0
cd "$PROJECT_ROOT"

# --- Stage 1: memory ---------------------------------------------------------
if command -v forge-memory >/dev/null 2>&1 && [ -d ".forge/memory" ]; then
  forge-memory consolidate >/dev/null 2>&1 || true
  forge-memory sync >/dev/null 2>&1 || true
fi

# --- Common git checks (used by Stage 2 and Stage 3) ------------------------
command -v git >/dev/null 2>&1 || exit 0
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || exit 0
HEAD_SHA=$(git rev-parse HEAD 2>/dev/null || echo "")
[ -z "$HEAD_SHA" ] && exit 0

TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
TS_SLUG=$(date -u +"%Y-%m-%d-%H%M%S")

# --- Stage 2: wiki (skipped if no .forge/wiki/) -----------------------------
if [ -d ".forge/wiki" ]; then
  STATE_SHA_FILE=".forge/wiki/.last-ingest-sha"
  if [ -f "$STATE_SHA_FILE" ]; then
    LAST_SHA=$(tr -d '[:space:]' < "$STATE_SHA_FILE")
  else
    LAST_SHA=""
  fi

  NEW_COMMITS=""
  if [ -n "$LAST_SHA" ] && git cat-file -e "$LAST_SHA^{commit}" 2>/dev/null; then
    NEW_COMMITS=$(git log --pretty=format:"%h|%s" "${LAST_SHA}..HEAD" 2>/dev/null || true)
  else
    NEW_COMMITS=$(git log -1 --pretty=format:"%h|%s" HEAD 2>/dev/null || true)
  fi

  UNCOMMITTED=$(git status --porcelain 2>/dev/null | awk '{print $2}' | sort -u)

  if [ -n "$NEW_COMMITS" ] || [ -n "$UNCOMMITTED" ]; then
    mkdir -p ".forge/wiki/raw/notes"
    NOTE_FILE=".forge/wiki/raw/notes/auto-${TS_SLUG}.md"

    {
      echo "---"
      echo "generated: ${TS}"
      echo "source: stop-hook"
      echo "---"
      echo
      echo "# Auto-capture ${TS}"
      echo
      if [ -n "$NEW_COMMITS" ]; then
        echo "## Commits since last capture"
        echo
        echo '```'
        printf '%s\n' "$NEW_COMMITS" | while IFS='|' read -r sha subj; do
          [ -z "$sha" ] && continue
          echo "${sha} ${subj}"
        done
        echo '```'
        echo
      fi
      if [ -n "$UNCOMMITTED" ]; then
        echo "## Uncommitted files"
        echo
        echo '```'
        printf '%s\n' "$UNCOMMITTED"
        echo '```'
        echo
      fi
    } > "$NOTE_FILE"

    LOG_FILE=".forge/wiki/log.md"
    [ -f "$LOG_FILE" ] || printf '# Wiki Log\n\n' > "$LOG_FILE"
    COMMIT_COUNT=0
    [ -n "$NEW_COMMITS" ] && COMMIT_COUNT=$(printf '%s\n' "$NEW_COMMITS" | wc -l | tr -d ' ')
    UNCOMMIT_COUNT=0
    [ -n "$UNCOMMITTED" ] && UNCOMMIT_COUNT=$(printf '%s\n' "$UNCOMMITTED" | wc -l | tr -d ' ')
    printf -- "- %s auto-capture: %s commits, %s uncommitted -> %s\n" \
      "$TS" "$COMMIT_COUNT" "$UNCOMMIT_COUNT" "$NOTE_FILE" >> "$LOG_FILE"

    PENDING=".forge/wiki/pending-ingest.yaml"
    if [ ! -f "$PENDING" ]; then
      {
        echo "# Auto-generated by forge-memory-sync Stop hook."
        echo "# Consumed by the FORGE hub at session start (see forge/SKILL.md)."
        echo "sources:"
      } > "$PENDING"
    fi
    {
      echo "  - type: stop-capture"
      echo "    generated: ${TS}"
      echo "    note: ${NOTE_FILE}"
      if [ -n "$NEW_COMMITS" ]; then
        echo "    commits:"
        printf '%s\n' "$NEW_COMMITS" | while IFS='|' read -r sha subj; do
          [ -z "$sha" ] && continue
          safe_subj=$(printf '%s' "$subj" | sed 's/"/\\"/g')
          echo "      - sha: ${sha}"
          echo "        subject: \"${safe_subj}\""
        done
      fi
      if [ -n "$UNCOMMITTED" ]; then
        echo "    uncommitted:"
        printf '%s\n' "$UNCOMMITTED" | while read -r f; do
          [ -z "$f" ] && continue
          echo "      - ${f}"
        done
      fi
    } >> "$PENDING"

    printf '%s\n' "$HEAD_SHA" > "$STATE_SHA_FILE"
  fi
fi

# --- Stage 3: release detection ---------------------------------------------
# Runs independently of Stage 2. Detects if HEAD is a release bump and queues
# a flow-state-pending.yaml entry so the hub updates flow-state.yaml prod_state
# on the next session start (Startup Protocol step 0b).
detect_release_tag() {
  local tag
  tag=$(git tag --points-at HEAD 2>/dev/null | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+' | head -n1 || true)
  if [ -n "$tag" ]; then
    echo "$tag"
    return 0
  fi
  local subj
  subj=$(git log -1 --pretty=format:'%s' HEAD 2>/dev/null || echo "")
  if [[ "$subj" =~ chore\(release\):[[:space:]]*(v[0-9]+\.[0-9]+\.[0-9]+) ]]; then
    echo "${BASH_REMATCH[1]}"
    return 0
  fi
  return 1
}

RELEASE_TAG=$(detect_release_tag || true)
if [ -n "$RELEASE_TAG" ] && [ -d ".forge" ]; then
  RELEASE_SYNC=".forge/flow-state-pending.yaml"
  RELEASE_DATE=$(git log -1 --pretty=format:'%cI' HEAD 2>/dev/null || echo "$TS")
  if [ ! -f "$RELEASE_SYNC" ]; then
    {
      echo "# Auto-generated by forge-memory-sync Stop hook."
      echo "# Consumed by the FORGE hub at session start (Startup Protocol step 0b)."
      echo "# The hub merges these entries into .forge/flow-state.yaml prod_state"
      echo "# (backend_version, last_release_commit, last_release_at, release_history)"
      echo "# without touching any other section, then deletes this file."
      echo "releases:"
    } > "$RELEASE_SYNC"
  fi
  if ! grep -q "sha: ${HEAD_SHA}" "$RELEASE_SYNC" 2>/dev/null; then
    {
      echo "  - tag: ${RELEASE_TAG}"
      echo "    sha: ${HEAD_SHA}"
      echo "    date: ${RELEASE_DATE}"
      echo "    detected_at: ${TS}"
    } >> "$RELEASE_SYNC"
  fi
fi

exit 0
